import React from "react";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";
import {GiHamburgerMenu} from "react-icons/gi";

function Layout({ title,  children, admin=true}){
    return (
        <>
            <Head>
                <title>{title ? title + " - Ferreteria La Ruta" : "Ferreteria La Ruta"}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <div className="flex flex-col justify-between h-screen">
                    <header>
                        <nav className="w-screen shadow-lg flex justify-between h-10 items-center px-5">
                            {admin ? (<button className="absolute"></button>):""}
                            <Link href="/">
                                <h1 className="font-bold text-lg">FLR</h1>
                            </Link>
                            <div className="flex">
                                {admin ? (<Link href="/admin/dashboard">Admin</Link>) : ""}
                                <Link href="/cart"><p className="px-3">Cart</p></Link>
                                <Link href="/login">Login</Link>
                            </div>
                        </nav>
                    </header>
                    <main>
                        {children}
                    </main>
                    <footer className="flex w-full justify-center py-2">
                        <p className="font-bold">Copyright © Ferreteria La Ruta 2023</p>
                    </footer>
                </div>
            </body>
        </>
    );
}

export default dynamic(()=> Promise.resolve(Layout), {ssr : false})